remove import tests for private modules
Fails if we don't set an experimental environment variable:
```
import: 'numpy.core._rational_tests'
RuntimeError: The new DType API is currently in an exploratory phase and should NOT be used for production code.  Expect modifications and crashes!  To experiment with the new API you must set `NUMPY_EXPERIMENTAL_DTYPE_API=1` as an environment variable.
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/numpy_1685410914098/test_tmp/run_test.py", line 95, in <module>
    import numpy.core._umath_tests
```